name: srnaflow_dc

services:
  srnaflow:
    image: ghcr.io/zajakin/srnaflow
    ports:
      - "3838:3838"
    volumes:
      - ${SRNAFLOW_DIR:?err}:/srv/shiny-server/www/
      - ${SRNAFLOW_UPLOAD:?err}:/srv/shiny-server/www/upload
    restart: unless-stopped
